### ISSUE TITLE
Duplication steps problem

### ISSUE THREAD

**Issue by varivoda** [sbtqa/page-factory#33] opened 2017-02-20 07:41 UTC
There is duplication steps problem when using page-factory and swing-back together.

**Comment by kosteman** [comment] 2017-02-28 04:40
can't reproduce.
tested on versions page-factory-1.3.5 and swing-back-1.0.1-alpha with feature:
```
* user is on the page "Landing"
* user (fill the field) "email" "mkypers@gmail.com"
* user (wait for button animated)
* user (click the button) "Send"
```

@varivoda can you pass me the project with this problem?

**Comment by varivoda** [comment] 2017-02-28 09:33
I ran it on versions page-factory-1.2.2 and swing-back-1.0.0.
It works fine on page-factory-1.3.5 and swing-back-1.0.1-alpha.

**Comment by clicman** [comment] 2017-02-28 13:23
It is not enough. You should to migrate to i18n and try again, because in some cases it can get first stepdef of it.

**Comment by varivoda** [comment] 2017-03-24 07:57
There are step conflicts again.
I created new repository with test demonstrated these conflicts. 
https://github.com/sbtqa/swingback-test

**Comment by clicman** [comment] 2017-03-24 08:11
https://github.com/sbtqa/swingback-test/blob/master/pom.xml
Change this shitty pom

**Comment by varivoda** [comment] 2017-03-24 08:34
The shitty pom is changed to another one

**Comment by clicman** [comment] 2017-03-24 09:28
Why i18n isn`t in master?

**Comment by varivoda** [comment] 2017-03-24 09:43
Pull request is megred.

**Comment by clicman** [comment] 2017-03-24 10:01
So now we see the problem. Let's find the way to fix it gracefully

**Comment by clicman** [comment] 2017-03-24 10:28
Thoughts on the draft.
* Add prefixes on parse for all projects in glue.
* On call unique stepdef for needed project do some context change
* Use it like a pro
* On call unique stepdef for another project do some context change
* Use it like a pro on another context

**Comment by varivoda** [comment] 2017-03-24 11:02
Nice idea.
But i think we should add prefixes to step defs during runtime in case when we use a few frameworks at one time.
We can add strategy property into application.properties, for example

multiple.frameworks.mode.enable = true/false

If we have false - use standart schema to run tests. 
in other case - add some prefixes into glue steps and feature steps during runtime

**Comment by clicman** [comment] 2017-03-24 11:05
No.  It should the only one behavior which wrapped automatically and which
not affects to end projects.
пт, 24 марта 2017 г. в 18:02, varivoda <notifications@github.com>:

**Comment by clicman** [comment] 2017-05-04 08:59
Fixed in upstream

**Closed** 2017-05-04 08:58 UTC
Labels: bug
